#!/usr/bin/env python3
"""Build an isolated replica of the TriggerBOFF harness, so quality can be measured
end-to-end — real agent loop, real tools, real SOUL — without touching production.

WHY
---
Every measurement so far called a model API directly. That measures the MODEL, and it
bypassed Hermes entirely. It produced a false alarm: 12/20 "empty" replies looked like a
delivery defect, but Hermes retries reasoning-only output
(`run_agent.py::_has_content_after_think_block` — "reasoning-only output is retried"), so
those never reach a user. Measuring the model instead of the harness gave the wrong answer.

This builds a second HERMES_HOME on this box — same SOUL.md, same property plugin, same
tools as the Railway harness — so `hermes -z` runs the genuine loop and we can measure
what a user would actually receive.

TWO ARMS, SAME REPLICA
----------------------
`cli` is the platform a one-shot run uses. Both arms are configured on that platform so
only the variable under test changes:

  web arm      : toolset hermes-api-server + the corrected api_server hint
  telegram arm : toolset hermes-telegram   + the Telegram hint (+ its rich-messages add-on)

Same model, same SOUL, same tools, same questions. The gap between them is the parity
gap, measured directly. That is the thing being optimised.
"""
from __future__ import annotations

import importlib.util
import os
import shutil
import subprocess
import sys
from pathlib import Path

REP = Path("/data/.hermes-replica")
HARNESS = Path("/data/repos/sydney-property-harness")
HERMES_SRC = Path("/opt/hermes-agent")

BASE_CONFIG = """# Replica config — generated by replica_setup.py. Do not hand-edit.
model: {model}
provider: openrouter

agent:
  max_turns: 40

# The one-shot run is platform "cli"; both arms are configured there so the platform
# itself is not a variable.
platform_toolsets:
  cli:
    - {toolset}

platform_hints:
  cli:
    replace: |
{hint}
"""


def _api_hint() -> str:
    spec = importlib.util.spec_from_file_location(
        "aph", str(HARNESS / "scripts" / "apply_platform_hints.py"))
    aph = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(aph)
    return aph.HINT


def _telegram_hint() -> str:
    """What Telegram users get: the static hint plus the rich-messages add-on, as
    assembled by agent/system_prompt.py::platform_hint()."""
    sys.path.insert(0, str(HERMES_SRC))
    from agent.prompt_builder import PLATFORM_HINTS, TELEGRAM_RICH_MESSAGES_HINT
    base = PLATFORM_HINTS.get("telegram", "")
    return base.rstrip() + " " + TELEGRAM_RICH_MESSAGES_HINT


def build(model: str = "z-ai/glm-5.3", arm: str = "web") -> Path:
    """Materialise (or refresh) the replica. Idempotent."""
    REP.mkdir(parents=True, exist_ok=True)

    shutil.copy(HARNESS / "docker" / "SOUL.md", REP / "SOUL.md")

    (REP / "tools").mkdir(exist_ok=True)
    for tool in (HARNESS / "tools").glob("*.py"):
        shutil.copy(tool, REP / "tools" / tool.name)

    plug = REP / "plugins"
    plug.mkdir(exist_ok=True)
    src_plug = HARNESS / "plugins"
    for d in src_plug.iterdir():
        if d.is_dir():
            dst = plug / d.name
            if dst.exists():
                shutil.rmtree(dst)
            shutil.copytree(d, dst)

    toolset = "hermes-api-server" if arm == "web" else "hermes-telegram"
    hint = _api_hint() if arm == "web" else _telegram_hint()
    indented = "\n".join("      " + line if line else "" for line in hint.splitlines())
    (REP / "config.yaml").write_text(
        BASE_CONFIG.format(model=model, toolset=toolset, hint=indented), encoding="utf-8")

    # Credentials: read from the builder container's env, never printed.
    env = {}
    for part in open("/proc/1/environ", "rb").read().split(b"\0"):
        if b"=" in part:
            k, v = part.split(b"=", 1)
            env[k.decode()] = v.decode(errors="replace")
    lines = [f"{k}={env[k]}" for k in
             ("OPENROUTER_API_KEY", "DOMAIN_API_KEY", "TFNSW_API_KEY", "TAVILY_API_KEY")
             if env.get(k)]
    (REP / ".env").write_text("\n".join(lines) + "\n", encoding="utf-8")
    os.chmod(REP / ".env", 0o600)
    return REP


def run(question: str, model: str | None = None, timeout: int = 300) -> dict:
    """One-shot agent run. Returns the visible answer plus timing."""
    import time
    cmd = ["hermes", "-z", question]
    if model:
        cmd += ["-m", model, "--provider", "openrouter"]
    t0 = time.time()
    try:
        p = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout,
                           env={**os.environ, "HERMES_HOME": str(REP), "HOME": str(REP)})
        out = (p.stdout or "").strip()
        return {"ok": p.returncode == 0, "answer": out, "seconds": round(time.time() - t0, 1),
                "stderr": (p.stderr or "")[-400:]}
    except subprocess.TimeoutExpired:
        return {"ok": False, "answer": "", "seconds": round(time.time() - t0, 1),
                "stderr": f"timeout after {timeout}s"}


if __name__ == "__main__":
    arm = sys.argv[1] if len(sys.argv) > 1 else "web"
    model = sys.argv[2] if len(sys.argv) > 2 else "z-ai/glm-5.3"
    build(model, arm)
    print(f"replica built: {REP}  arm={arm}  model={model}")
    r = run("What have homes actually sold for in MARRICKVILLE in the last 6 months? "
            "Give me real numbers.", model)
    print(f"  ok={r['ok']}  {r['seconds']}s  {len(r['answer'])} chars")
    if r["answer"]:
        print("  ---")
        print("  " + r["answer"][:700].replace("\n", "\n  "))
    elif r["stderr"]:
        print("  stderr:", r["stderr"])
